-- =============================================================================
-- Finance Dashboard - SQL Schema Reference
-- =============================================================================
-- Database: H2 (embedded, file-based) — compatible with MySQL/PostgreSQL
-- This schema is auto-generated by Hibernate from JPA entities.
-- Provided here for documentation, manual inspection, and migration reference.
--
-- To switch to PostgreSQL:
--   1. Replace H2 dependency in pom.xml with postgresql driver
--   2. Update application.properties datasource URL/driver
--   3. Change spring.jpa.database-platform to PostgreSQLDialect
-- =============================================================================

-- -----------------------------------------------------------------------------
-- TABLE: users
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id          BIGINT          NOT NULL AUTO_INCREMENT,
    full_name   VARCHAR(100)    NOT NULL,
    email       VARCHAR(150)    NOT NULL,
    password    VARCHAR(255)    NOT NULL,          -- bcrypt hash
    role        VARCHAR(20)     NOT NULL,          -- VIEWER | ANALYST | ADMIN
    active      BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('VIEWER', 'ANALYST', 'ADMIN'))
);

-- Index for fast login lookups
CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_role  ON users (role);

-- -----------------------------------------------------------------------------
-- TABLE: financial_records
-- -----------------------------------------------------------------------------
CREATE TABLE financial_records (
    id                BIGINT          NOT NULL AUTO_INCREMENT,
    amount            DECIMAL(15,2)   NOT NULL,        -- BigDecimal precision
    type              VARCHAR(10)     NOT NULL,        -- INCOME | EXPENSE
    category          VARCHAR(100)    NOT NULL,
    transaction_date  DATE            NOT NULL,
    notes             VARCHAR(500),
    deleted_at        TIMESTAMP       NULL DEFAULT NULL, -- NULL = active (soft delete)
    created_by        BIGINT          NOT NULL,          -- FK → users.id
    created_at        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT fk_records_user    FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT chk_records_type   CHECK (type IN ('INCOME', 'EXPENSE')),
    CONSTRAINT chk_records_amount CHECK (amount > 0)
);

-- Indexes for frequent filter/aggregate queries
CREATE INDEX idx_record_type        ON financial_records (type);
CREATE INDEX idx_record_category    ON financial_records (category);
CREATE INDEX idx_record_date        ON financial_records (transaction_date);
CREATE INDEX idx_record_deleted     ON financial_records (deleted_at);     -- partial-index equivalent
CREATE INDEX idx_record_created_by  ON financial_records (created_by);

-- =============================================================================
-- SEED DATA (matches DataSeeder.java — for manual seeding / reference)
-- =============================================================================

-- Default admin user  (password: admin123)
INSERT INTO users (full_name, email, password, role, active)
VALUES (
    'Admin User',
    'admin@finance.com',
    '$2a$12$...bcrypt_hash_of_admin123...',
    'ADMIN',
    TRUE
);

-- Analyst user  (password: analyst123)
INSERT INTO users (full_name, email, password, role, active)
VALUES (
    'Alice Analyst',
    'analyst@finance.com',
    '$2a$12$...bcrypt_hash_of_analyst123...',
    'ANALYST',
    TRUE
);

-- Viewer user  (password: viewer123)
INSERT INTO users (full_name, email, password, role, active)
VALUES (
    'Victor Viewer',
    'viewer@finance.com',
    '$2a$12$...bcrypt_hash_of_viewer123...',
    'VIEWER',
    TRUE
);

-- NOTE: Actual bcrypt hashes are generated at runtime by DataSeeder.java
--       The hash placeholders above are for illustration only.

-- =============================================================================
-- ACCESS CONTROL MATRIX (enforced at Spring Security + @PreAuthorize level)
-- =============================================================================
--
--  Endpoint                            VIEWER   ANALYST   ADMIN
--  ─────────────────────────────────────────────────────────────
--  POST   /api/auth/login               ✓        ✓        ✓
--  POST   /api/auth/register            ✓        ✓        ✓
--  GET    /api/dashboard/summary        ✓        ✓        ✓
--  GET    /api/records                  ✗        ✓        ✓
--  GET    /api/records/{id}             ✗        ✓        ✓
--  POST   /api/records                  ✗        ✗        ✓
--  PUT    /api/records/{id}             ✗        ✗        ✓
--  DELETE /api/records/{id}             ✗        ✗        ✓   (soft delete)
--  GET    /api/users                    ✗        ✗        ✓
--  POST   /api/users                    ✗        ✗        ✓
--  PUT    /api/users/{id}               ✗        ✗        ✓
--  PATCH  /api/users/{id}/toggle-status ✗        ✗        ✓
--  DELETE /api/users/{id}              ✗        ✗        ✓
--
-- =============================================================================
